POST http://localhost:8090/transactions?amount=50
Accept: application/json

###
POST http://localhost:8080/transactions?amount=80
Accept: application/json

###
POST http://localhost:8080/transactions
Content-Type: application/json
Accept: application/json

{
  "amount": 200,
  "reference": "tuition",
  "receivingUser": "Yong Qin"
}

###
POST http://localhost:8080/transactions
Content-Type: application/json
Accept: application/json

{
  "amount": -5,
  "reference": ""
}

###
GET http://localhost:8080/account/15beefd9-d444-4119-a475-0b304c56cacf
Accept: application/json